### ISSUE TITLE
The Administrators Users and Groups Details section show the last user processed

### ISSUE THREAD

**Issue by rebelinux** [AsBuiltReport/AsBuiltReport.VMware.Horizon#12]
https://github.com/AsBuiltReport/AsBuiltReport.VMware.Horizon/blob/15e7833b5afb8da44a8f88387d09820be1c6d9c9/Src/Private/Get-AbrHRZAdminGroup.ps1#L85

The section shows the last user processed. I think the correct sentence for the section would be:

` section -Style Heading4 "Administrators Users and Groups Details" { `

![Screenshot from 2024-01-13 22-13-50](https://github.com/AsBuiltReport/AsBuiltReport.VMware.Horizon/assets/1002783/fb1bf2cc-1fe8-4b5f-8070-d5e11499318f)

**Comment by childebrandt42** [comment]
Fixing in next update

**Comment by childebrandt42** [comment]
Fixed in the last merge
