### ISSUE TITLE
The Connection Server section under Domains has a misleading title

### ISSUE THREAD

**Issue by rebelinux** [AsBuiltReport/AsBuiltReport.VMware.Horizon#13]
https://github.com/AsBuiltReport/AsBuiltReport.VMware.Horizon/blob/15e7833b5afb8da44a8f88387d09820be1c6d9c9/Src/Private/Get-AbrHRZDomains.ps1#L69

I am a little confused by the name of this section. A suggestion would be to call it Domain Status or something like that, reflecting the purpose of the section.

![Screenshot from 2024-01-13 22-33-16](https://github.com/AsBuiltReport/AsBuiltReport.VMware.Horizon/assets/1002783/5b607ed6-d384-4c8e-8839-c557a9f44096)

**Comment by childebrandt42** [comment]
Added to next build release.

**Comment by childebrandt42** [comment]
Fixed with last merge
