### ISSUE TITLE
Running AsbuiltReport for Vmware.Horizon

### ISSUE THREAD

**Issue by TAThacker** [AsBuiltReport/AsBuiltReport.VMware.Horizon#6]
**Describe the bug**
When running the New-AsBuiltReport command for Report vmware.Horizon we receive the following error.

The property 'Number' can not be found on this object. Ensure the property exists.

**To Reproduce**
Run:

PS C:\> $Creds = Get-Credential
PS C:\> New-AsBuiltReport -Report VMware.Horizon -Target 'Horizon-cs-01.corp.local' -Credential $Creds -Format Html,Text -OutputFolderPath 'C:\Users\Jon\Documents' -EnableHealthCheck

**Comment by rebelinux** [comment]
Can you run the report with the -Verbose command and send me the output?

jcolonf@zenprsolutions.com

Regards,

**Comment by TAThacker** [comment]
> 

I have sent you an email.

**Comment by rebelinux** [comment]
I was able to replicate the error, it happens when the username was specified without the Domain part.

"Valid Domain is Required"

Make sure that the user name is specified as username@domain.local.

Wrong Format:
```
PS /home/rebelinux> $password = ConvertTo-SecureString "XXXXXXX" -AsPlainText -Force                                                                       
PS /home/rebelinux> $Cred = New-Object System.Management.Automation.PSCredential ("administrator", $password)
PS /home/rebelinux> Connect-HVServer -Server 192.168.7.202 -Credential $Cred -ErrorAction Stop               
Connect-HVServer: Valid Domain is required <== Same Error
PS /home/rebelinux> 
```

Correct Format:
```
PS /home/rebelinux> $password = ConvertTo-SecureString "XXXXXX" -AsPlainText -Force                        
PS /home/rebelinux> $Cred = New-Object System.Management.Automation.PSCredential ("administrator@pharmax.local", $password)                                 
PS /home/rebelinux> Connect-HVServer -Server 192.168.7.202 -Credential $Cred -ErrorAction Stop                             
                     
ServiceUri          : https://192.168.7.202/view-vlsi/sdk
RefCount            : 2
User                : administrator
Domain              : pharmax.local
Id                  : /ViewServer=administrator@192.168.7.202/
SessionSecret       : 3ec68063-326f-4de4-a6e6-c0b6f4358c20
IsConnected         : True
ExtensionData       : VMware.Hv.Services
Name                : 192.168.7.202
Uid                 : /ViewServer=administrator@192.168.7.202/
Client              : VMware.VimAutomation.HorizonView.Impl.V1.ViewServerClientImpl
EncryptionWarning   : 
EncryptionException : 

PS /home/rebelinux> 
```

Thank you for reporting the situation. I will be updating the documentation to specify the user format requirements.

**Comment by rebelinux** [comment]
I was able to replicate the error you report it happens when the user is specified without the Domain part.

Make sure that the username is specified as follows: administrator@domain.local

Wrong Format: $Cred = New-Object System.Management.Automation.PSCredential ("administrator", $password)

```
PS /home/xxxxxxx> $password = ConvertTo-SecureString "XXXXX" -AsPlainText -Force                                                                       
PS /home/xxxxxxx> $Cred = New-Object System.Management.Automation.PSCredential ("administrator", $password) 
PS /home/xxxxxxx> New-AsBuiltReport -Report VMware.Horizon -AsBuiltConfigFilePath /home/xxx/script/AsBuiltReport.json -OutputFolderPath /home/xxxx/script -Target 192.168.7.202 -Format HTML -EnableHealthCheck -Credential $cred -ReportConfigFilePath /home/xxx/script/AsbuiltReport.VMware.Horizon.json
Please wait while the VMware Horizon As Built Report is being generated.
WARNING: [ 10:29:55:561 ] [ Document ] - Please refer to the AsBuiltReport.VMware.Horizon github website for more detailed information about this project.
WARNING: [ 10:29:55:562 ] [ Document ] - Do not forget to update your report configuration file after each new version release.
WARNING: [ 10:29:55:563 ] [ Document ] - Documentation: https://github.com/AsBuiltReport/AsBuiltReport.VMware.Horizon
WARNING: [ 10:29:55:564 ] [ Document ] - Issues or bug reporting: https://github.com/AsBuiltReport/AsBuiltReport.VMware.Horizon/issues
WARNING: [ 10:29:57:470 ] [ Document ] - Valid Domain is required
VMware Horizon As Built Report 'VMware Horizon As Built Report' has been saved to '/home/xxxxxxx/script'.
PS /home/xxxxxxx> 
```

Correct Format: $Cred = New-Object System.Management.Automation.PSCredential ("administrator@domain.local", $password)

```
PS /home/xxxxxxx> New-AsBuiltReport -Report VMware.Horizon -AsBuiltConfigFilePath /home/xxxxx/script/AsBuiltReport.json -OutputFolderPath /home/xxxxxxx/script -Target 192.168.7.202 -Format HTML -EnableHealthCheck -Credential $cred -ReportConfigFilePath /home/xxxxx/script/AsbuiltReport.VMware.Horizon.json
Please wait while the VMware Horizon As Built Report is being generated.
WARNING: [ 10:35:50:908 ] [ Document ] - Please refer to the AsBuiltReport.VMware.Horizon github website for more detailed information about this project.
WARNING: [ 10:35:50:909 ] [ Document ] - Do not forget to update your report configuration file after each new version release.
WARNING: [ 10:35:50:910 ] [ Document ] - Documentation: https://github.com/AsBuiltReport/AsBuiltReport.VMware.Horizon
WARNING: [ 10:35:50:911 ] [ Document ] - Issues or bug reporting: https://github.com/AsBuiltReport/AsBuiltReport.VMware.Horizon/issues
VMware Horizon As Built Report 'VMware Horizon As Built Report' has been saved to '/home/xxxxxxx/script'.
PS /home/xxxxxxx> 
```

Thank you for reporting the situation. I will be updating the documentation to specify the user format requirements.

**Comment by ssimps4** [comment]
Hi @rebelinux,
I'm still seeing the same issue occur on my end while trying to use the Horizon AsBuilt module.
When I specify the administrator@domain.com and password I still receive the error:

New-AsBuiltReport : The property 'Number' cannot be found on this object. Verify that the property exists.
At line:1 char:1

I'm currently running version 8.10 of VMware Horizon in a test lab.
Some assistance would be greatly appreciated!

**Comment by rebelinux** [comment]
Can you run the report with the -verbose option and send me the output to jcolonf@zenprsolutions.com?

**Comment by ssimps4** [comment]
Thanks. I have sent over an email with the details of the verbose report.

**Comment by rebelinux** [comment]
Can you do a test and try to connect to your CS server from a powershell console?

`Connect-HVServer -Server horizon-cs -Credential (Get-Credential) `

**Comment by ssimps4** [comment]
Connect-HVServer : Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Connect-HVServer -Server ss-connsvr01.sslab.ca -Credential (Get-Crede ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-HVServer], Exception
    + FullyQualifiedErrorId : System.Exception,VMware.VimAutomation.HorizonView.Commands.Cmdlets.ConnectHVServer

**Comment by ssimps4** [comment]
@rebelinux I will try an fix this prior to bugging you about the reports. Stay tuned!
